- name: "Debian/Ubintu | Ensure gpg is installed"
  become: true
  apt:
    pkg: gpg
    state: present

- name: "Debian/Ubuntu | Installing repository key"
  become: true
  apt_key:
    url: https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt

- name: "Debian/Ubuntu | Installing repository"
  become: true
  apt_repository:
    repo: "deb https://updates.atomicorp.com/channels/atomic/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present

- name: "Debian/Ubuntu | Install ossec-hids"
  become: true
  apt:
    pkg: ossec-hids-agent
    state: present

- name: "Set ossec deploy facts for Debian"
  set_fact:
    ossec_server_config_filename: ossec.conf
    ossec_init_name: ossec
    ossec_authd_init_name: ossec
