---
- name: Restart sshd
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: restarted
  when: ssh_server_enabled | bool
  become: true

- name: Reboot the system
  ansible.builtin.reboot:
    msg: "Rebooting to apply SELinux changes"
    reboot_timeout: 300
  become: true
