- name: Init Machines
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install ACL
      become: true
      ansible.builtin.apt:
        name: "acl"

- hosts: server
  roles:
    - hardening

- hosts: audit
  roles:
    - role: ssh_authorize_targets
      vars:
        ssh_authorize_user_targets: "{{ groups['client'] }}"
