- name: Init Machines
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install basics packages
      become: true
      ansible.builtin.apt:
        name: ["acl"]
      delay: 15

- hosts: server
  roles:
    - hardening

- hosts: audit
  roles:
    - role: ssh_authorize_targets
      vars:
        ssh_authorize_user_targets: "{{ groups['client'] }}"
