- name: My first play
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

- hosts: client
  roles:
    - server
    - postgres

- hosts: audit
  roles:
    - ossec-server



