- name: Init Machines
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Remove apparmor
      become: true
      ansible.builtin.apt:
        name: "apparmor"
        state: absent
        purge: true

    - name: Install basics packages
      become: true
      ansible.builtin.apt:
        name: ["linux-generic", "acl", "selinux-basics", "selinux-utils"]

- hosts: server
  roles:
    - hardening

- hosts: audit
  roles:
    - role: ssh_authorize_targets
      vars:
        ssh_authorize_user_targets: "{{ groups['client'] }}"
