- name: Init Machines
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install ACL
      become: true
      ansible.builtin.apt:
        name: "acl"
        update_cache: yes
       

- hosts: client
  roles:
    - server
    - postgres

- hosts: audit
  roles:
    - ossec-server
