- name: Init Machines
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Wait for apt lock to be released
      shell: |
        while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; do
          echo "Waiting for other apt/dpkg processes to finish..."
          sleep 5
        done
      retries: 5
      delay: 10
      register: apt_lock_check
      until: apt_lock_check.rc == 0

    - name: Install basics packages
      become: true
      ansible.builtin.apt:
        name: ["acl"]
        state: present
        update_cache: true
      retries: 5
      delay: 10
      register: apt_result
      until: apt_result is succeeded

# - hosts: audit
#   become: true
#   roles:
#     - wazuh-manager
#   vars:
#     instances:
#       node1:
#         name: pve # Important: must be equal to indexer_node_name.
#         ip: 127.0.0.1
#         role: indexer
#     ansible_shell_allow_world_readable_temp: true

- hosts: server
  become: true
  roles:
    - wazuh-agent
    - hardening
  vars:
    wazuh_managers: "{{ groups['audit'] }}"
