- name: Configuring hardening
  hosts: audit
  become: yes
  roles:
    - wazuh-manager
  vars:
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: 127.0.0.1
        role: indexer
    ansible_shell_allow_world_readable_temp: true

- name: Example Wazuh Configuration
  hosts: server
  become: yes
  roles:
    - wazuh-agent
  vars:
    wazuh_managers: "{{ groups['audit'] }}"
