---
- name: Install selinux dependencies when selinux is installed
  become: true
  ansible.builtin.apt:
    name: "{{ ssh_selinux_packages }}"
    state: present

- name: Configure selinux | selinux-01
  become: true
  ansible.posix.selinux:
    policy: "{{ os_selinux_policy }}"
    state: "{{ os_selinux_state }}" # noqa args - see https://github.com/ansible/ansible-lint/issues/2930

- name: restart the server
  shell: (sleep 2 && shutdown -r now) &
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for the server to come back
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 5

- name: Authorize the following ports for selinux - {{ ssh_server_ports }}
  become: true
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  loop: "{{ ssh_server_ports }}"

- name: Check if ssh_password module is already installed
  ansible.builtin.shell: set -o pipefail && semodule -l | grep ssh_password
  args:
    executable: /bin/bash
  register: ssh_password_module
  failed_when: false
  changed_when: false
  check_mode: false
