---
- name: Protect sysctl.conf
  become: true
  ansible.builtin.file:
    path: /etc/sysctl.conf
    owner: root
    group: root
    mode: "0440"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Set Daemon umask, do config for rhel-family | NSA 2.2.4.1
  ansible.builtin.template:
    src: etc/sysconfig/rhel_sysconfig_init.j2
    dest: /etc/sysconfig/init
    owner: root
    group: root
    mode: "0544"
  when: ansible_facts.os_family == 'RedHat'

- name: Change sysctls
  when: ansible_virtualization_type not in ['docker', 'lxc', 'openvz']
  become: true
  block:
    - name: Change various sysctl-settings, look at the sysctl-vars file for documentation
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
        ignoreerrors: true
      with_dict: "{{ sysctl_config }}"
      when: item.key not in sysctl_unsupported_entries | default()

- name: Apply ufw defaults
  become: true
  ansible.builtin.template:
    src: etc/default/ufw.j2
    dest: /etc/default/ufw
    mode: "0644"
  when:
    - ufw_manage_defaults
    - ansible_facts.os_family == 'Debian'
  tags: ufw
