---
sshd_path: /usr/sbin/sshd
ssh_host_keys_dir: /etc/ssh
sshd_service_name: ssh
ssh_owner: root
ssh_group: root
ssh_host_keys_owner: root
ssh_host_keys_group: root
ssh_host_keys_mode: "0600"
ssh_selinux_packages:
  - auditd
  - selinux-basics
  - selinux-policy-default
  - policycoreutils-python-utils
  - checkpolicy

sshd_moduli_file: /etc/ssh/moduli

sshd_disable_crypto_policy: false
