postgresql_version: 14
postgresql_listen_address: "0.0.0.0"
postgresql_port: 5432
postgresql_data_directory: "/var/lib/postgres/{{ postgresql_version }}/main"
postgresql_max_connections: 100
postgresql_shared_buffers: "128MB"
postgresql_auth_users:
  - username: postgres
    password: postgres@pass
    database: null
