---
- name: Install PostgreSQL
  become: true
  ansible.builtin.apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present

- name: Ensure required dependencies are installed
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-psycopg2

- name: Install psycopg2 via pip 
  become: true
  ansible.builtin.pip:
    name: "psycopg2"
    state: present

# - name: Initialize PostgreSQL database
#   ansible.builtin.command:
#     cmd: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
#   args:
#     creates: "{{ postgresql_data_directory }}/PG_VERSION"

- name: Configure postgresql.conf
  become: true
  become_user: postgres
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: "0640"

- name: Configure pg_hba.conf
  become: true
  become_user: postgres
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0640"

- name: Start and enable PostgreSQL service
  ansible.builtin.service:
    name: "postgresql"
    state: started
    enabled: true

- name: Create PostgreSQL users and databases
  ansible.builtin.postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    db: "{{ item.database }}"
    state: present
  loop: "{{ postgresql_auth_users }}"
  become: true
  become_user: postgres
